### ISSUE TITLE
Add a Tutorial on how to perform offline debugging with ovs-offline

### ISSUE THREAD

**Issue by amorenoz** [amorenoz/ovs-dbg#40]
It should include the process of obtaining the needed information from

- k8s/oc
- osp w/ sos report latest changes
- generic system, w/o latest changes in sos (i.e: based on ovs-save)

And performing:
- basic ovs/ovn introspection
- appctl ofproto/trace
- ovn-detrace

**Comment by SalDaniele** [comment]
Absolutely!
