### ISSUE TITLE
ovs-offline: Seems to not support python virtualenv

### ISSUE THREAD

**Issue by lewisdenny** [amorenoz/ovs-dbg#69]
Install steps:
```
git clone https://github.com/amorenoz/ovs-dbg.git
cd ovs-dbg
virtualenv .venv && source .venv/bin/activate
pip install --upgrade pip
pip install .
```
Error:
```
❯ ovs-offline build

Error: context must be a directory: "/home/ldenny/ovs-dbg/.venv/containers/ovs-dbg"
```

Showing current `CONTAINER_PATH` var
```
echo $CONTAINER_PATH
/home/ldenny/ovs-dbg/.venv/bin/../containers/ovs-dbg
```
and actual location:
```
/home/ldenny/ovs-dbg/containers/ovs-dbg

**Comment by amorenoz** [comment]
Thanks @lewisdenny for reporting
@SalDaniele can you take a look at this one?

**Comment by amorenoz** [comment]
Right, "build" command will not work from the pip-installed version. Maybe if the Dockerfile is not found we can error and say something like:
"Cannot build the container locally, instead we will use quay.io/...."
