### ISSUE TITLE
Container won't start without required directories on the host

### ISSUE THREAD

**Issue by lewisdenny** [amorenoz/ovs-dbg#71]
`ovs-offline start` fails to run due to missing directories on the host

The error:
```
ovs-offline start
Error: statfs /tmp/ovs-offline/var-run/ovn_sb: no such file or directory
Error: statfs /tmp/ovs-offline/var-run/ovn_nb: no such file or directory
```

Resolution:
```
mkdir -p /tmp/ovs-offline/var-run/ovn_nb
mkdir -p /tmp/ovs-offline/var-run/ovn_sb
```

**Comment by amorenoz** [comment]
You cannot "start" the offline debugging session without first "collecting" information from sos report or database file.

But maybe we can print a nicer error message, e.g: "Working directory not found, please run ovs-offline collect-... first"

**Comment by lewisdenny** [comment]
Hi Sal, 

Yes you are correct, I am using `podman`, after creating the dirs all is fine. This is required even after collecting the information from a SoS report. 

I have left a comment on your PR
